import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:wiindy/models/api_response.dart';
import 'package:wiindy/models/current_weather.dart';
import 'package:wiindy/models/forecast_weather.dart';
import 'package:wiindy/repos/weather_repo.dart';
import 'package:wiindy/services/api_service.dart';

import 'weather_repo_test.mocks.dart';

@GenerateMocks([ApiService, WeatherRepo])
void main() {
  Get.put(ApiService());
  group('weatherRepoTest', () {
    test('returns an CurrentWeather if the api call completes successfully', () async {
      ApiService apiService = MockApiService();
      WeatherRepo weatherRepo = WeatherRepo(apiService: apiService);

      when(apiService.apiCall(
        route: 'current?key=9b3bf0fb00af4d2fad81c842ec6e90ea&city=London',
        requestMethod: RequestMethod.get,
      )).thenAnswer((_) {
        return Future.value(ApiResponse(isSuccess: true, data: {
          "count": 1,
          "data": [
            {
              "app_temp": 10.6,
              "aqi": 33,
              "city_name": "City of London",
              "clouds": 36,
              "country_code": "GB",
              "datetime": "2023-06-07:03",
              "dewpt": 8.9,
              "dhi": 0,
              "dni": 0,
              "elev_angle": -5.84,
              "ghi": 0,
              "gust": 6.17,
              "h_angle": -90,
              "lat": 51.51279,
              "lon": -0.09184,
              "ob_time": "2023-06-07 03:39",
              "pod": "d",
              "precip": 0,
              "pres": 1020.5,
              "rh": 92,
              "slp": 1022,
              "snow": 0,
              "solar_rad": 0,
              "sources": ["analysis", "AV975"],
              "state_code": "ENG",
              "station": "AV975",
              "sunrise": "03:44",
              "sunset": "20:14",
              "temp": 10.6,
              "timezone": "Europe/London",
              "ts": 1686109157,
              "uv": 0,
              "vis": 16,
              "weather": {"icon": "c02d", "description": "Few clouds", "code": 801},
              "wind_cdir": "NE",
              "wind_cdir_full": "northeast",
              "wind_dir": 39,
              "wind_spd": 3.6
            }
          ]
        }));
      });

      CurrentWeather currentWeather = await weatherRepo.getCurrentWeather(city: "London");
      expect(currentWeather, isA<CurrentWeather>());
    });

    test('returns an List<ForecastWeather> if the api call completes successfully', () async {
      ApiService apiService = MockApiService();
      WeatherRepo weatherRepo = WeatherRepo(apiService: apiService);

      when(apiService.apiCall(
        route: 'forecast/daily?key=9b3bf0fb00af4d2fad81c842ec6e90ea&days=7&city=London',
        requestMethod: RequestMethod.get,
      )).thenAnswer((_) {
        return Future.value(ApiResponse(
          isSuccess: true,
          data: {
            "city_name": "India",
            "country_code": "RS",
            "data": [
              {
                "app_max_temp": 23.1,
                "app_min_temp": 14.4,
                "clouds": 54,
                "clouds_hi": 71,
                "clouds_low": 64,
                "clouds_mid": 12,
                "datetime": "2023-06-07",
                "dewpt": 18.1,
                "high_temp": 22.6,
                "low_temp": 14.9,
                "max_dhi": null,
                "max_temp": 22.6,
                "min_temp": 14.4,
                "moon_phase": 0.776049,
                "moon_phase_lunation": 0.65,
                "moonrise_ts": 1686089161,
                "moonset_ts": 1686121892,
                "ozone": 345.9,
                "pop": 65,
                "precip": 5.2304688,
                "pres": 1000.9,
                "rh": 87,
                "slp": 1015.6,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686106428,
                "sunset_ts": 1686162292,
                "temp": 20.5,
                "ts": 1686121260,
                "uv": 8.2,
                "valid_date": "2023-06-07",
                "vis": 20.176,
                "weather": {"icon": "r02d", "description": "Moderate rain", "code": 501},
                "wind_cdir": "SSE",
                "wind_cdir_full": "south-southeast",
                "wind_dir": 152,
                "wind_gust_spd": 3.5,
                "wind_spd": 1.3
              },
              {
                "app_max_temp": 23.6,
                "app_min_temp": 14.9,
                "clouds": 60,
                "clouds_hi": 100,
                "clouds_low": 49,
                "clouds_mid": 10,
                "datetime": "2023-06-08",
                "dewpt": 17,
                "high_temp": 23.3,
                "low_temp": 16.1,
                "max_dhi": null,
                "max_temp": 23.3,
                "min_temp": 14.9,
                "moon_phase": 0.665629,
                "moon_phase_lunation": 0.69,
                "moonrise_ts": 1686177501,
                "moonset_ts": 1686213206,
                "ozone": 346.6,
                "pop": 50,
                "precip": 2.78125,
                "pres": 999.3,
                "rh": 89,
                "slp": 1014.1,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686192809,
                "sunset_ts": 1686248731,
                "temp": 19.1,
                "ts": 1686175260,
                "uv": 5.8,
                "valid_date": "2023-06-08",
                "vis": 23.928,
                "weather": {"icon": "r01d", "description": "Light rain", "code": 500},
                "wind_cdir": "SE",
                "wind_cdir_full": "southeast",
                "wind_dir": 142,
                "wind_gust_spd": 2.6,
                "wind_spd": 0.9
              },
              {
                "app_max_temp": 23.4,
                "app_min_temp": 16.1,
                "clouds": 60,
                "clouds_hi": 68,
                "clouds_low": 66,
                "clouds_mid": 26,
                "datetime": "2023-06-09",
                "dewpt": 17.9,
                "high_temp": 22.9,
                "low_temp": 16.3,
                "max_dhi": null,
                "max_temp": 22.9,
                "min_temp": 16.1,
                "moon_phase": 0.54702,
                "moon_phase_lunation": 0.72,
                "moonrise_ts": 1686265435,
                "moonset_ts": 1686304353,
                "ozone": 351.4,
                "pop": 75,
                "precip": 9.644531,
                "pres": 997.3,
                "rh": 93,
                "slp": 1011.9,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686279192,
                "sunset_ts": 1686335168,
                "temp": 19.2,
                "ts": 1686261660,
                "uv": 4.5,
                "valid_date": "2023-06-09",
                "vis": 22.909,
                "weather": {"icon": "r02d", "description": "Moderate rain", "code": 501},
                "wind_cdir": "SSE",
                "wind_cdir_full": "south-southeast",
                "wind_dir": 150,
                "wind_gust_spd": 3,
                "wind_spd": 1.1
              },
              {
                "app_max_temp": 27.3,
                "app_min_temp": 16.3,
                "clouds": 61,
                "clouds_hi": 16,
                "clouds_low": 66,
                "clouds_mid": 8,
                "datetime": "2023-06-10",
                "dewpt": 17,
                "high_temp": 26.8,
                "low_temp": 16,
                "max_dhi": null,
                "max_temp": 26.8,
                "min_temp": 16.3,
                "moon_phase": 0.427925,
                "moon_phase_lunation": 0.76,
                "moonrise_ts": 1686353128,
                "moonset_ts": 1686395319,
                "ozone": 353.5,
                "pop": 65,
                "precip": 5.1992188,
                "pres": 996.5,
                "rh": 85,
                "slp": 1010.4,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686365577,
                "sunset_ts": 1686421603,
                "temp": 20,
                "ts": 1686348060,
                "uv": 9.2,
                "valid_date": "2023-06-10",
                "vis": 23.42,
                "weather": {"icon": "r02d", "description": "Moderate rain", "code": 501},
                "wind_cdir": "WSW",
                "wind_cdir_full": "west-southwest",
                "wind_dir": 248,
                "wind_gust_spd": 2.8,
                "wind_spd": 1.4
              },
              {
                "app_max_temp": 24.1,
                "app_min_temp": 16,
                "clouds": 41,
                "clouds_hi": 34,
                "clouds_low": 26,
                "clouds_mid": 23,
                "datetime": "2023-06-11",
                "dewpt": 16.5,
                "high_temp": 23.9,
                "low_temp": 11.2,
                "max_dhi": null,
                "max_temp": 23.9,
                "min_temp": 16,
                "moon_phase": 0.315187,
                "moon_phase_lunation": 0.79,
                "moonrise_ts": 1686440702,
                "moonset_ts": 1686486160,
                "ozone": 354.5,
                "pop": 80,
                "precip": 13,
                "pres": 998.6,
                "rh": 82,
                "slp": 1011.2,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686451965,
                "sunset_ts": 1686508036,
                "temp": 19.9,
                "ts": 1686434460,
                "uv": 6.9,
                "valid_date": "2023-06-11",
                "vis": 18.534,
                "weather": {"icon": "r02d", "description": "Moderate rain", "code": 501},
                "wind_cdir": "SW",
                "wind_cdir_full": "southwest",
                "wind_dir": 225,
                "wind_gust_spd": 4.7,
                "wind_spd": 3.4
              },
              {
                "app_max_temp": 21.2,
                "app_min_temp": 11.2,
                "clouds": 18,
                "clouds_hi": 15,
                "clouds_low": 2,
                "clouds_mid": 15,
                "datetime": "2023-06-12",
                "dewpt": 11.4,
                "high_temp": 21.5,
                "low_temp": 12.5,
                "max_dhi": null,
                "max_temp": 21.5,
                "min_temp": 11.2,
                "moon_phase": 0.214497,
                "moon_phase_lunation": 0.82,
                "moonrise_ts": 1686527102,
                "moonset_ts": 1686576950,
                "ozone": 359.5,
                "pop": 0,
                "precip": 0,
                "pres": 1001.4,
                "rh": 81,
                "slp": 1014.3,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686538356,
                "sunset_ts": 1686594467,
                "temp": 15,
                "ts": 1686520860,
                "uv": 9.9,
                "valid_date": "2023-06-12",
                "vis": 24.128,
                "weather": {"icon": "c02d", "description": "Few clouds", "code": 801},
                "wind_cdir": "E",
                "wind_cdir_full": "east",
                "wind_dir": 85,
                "wind_gust_spd": 5.8,
                "wind_spd": 3.4
              },
              {
                "app_max_temp": 23.5,
                "app_min_temp": 12.5,
                "clouds": 32,
                "clouds_hi": 26,
                "clouds_low": 9,
                "clouds_mid": 25,
                "datetime": "2023-06-13",
                "dewpt": 13,
                "high_temp": 23.6,
                "low_temp": 16.4,
                "max_dhi": null,
                "max_temp": 23.6,
                "min_temp": 12.5,
                "moon_phase": 0.130305,
                "moon_phase_lunation": 0.86,
                "moonrise_ts": 1686614656,
                "moonset_ts": 1686667738,
                "ozone": 354.8,
                "pop": 0,
                "precip": 0,
                "pres": 999.8,
                "rh": 73,
                "slp": 1012.5,
                "snow": 0,
                "snow_depth": 0,
                "sunrise_ts": 1686624748,
                "sunset_ts": 1686680896,
                "temp": 18.4,
                "ts": 1686607260,
                "uv": 9.9,
                "valid_date": "2023-06-13",
                "vis": 24.128,
                "weather": {"icon": "c02d", "description": "Scattered clouds", "code": 802},
                "wind_cdir": "ENE",
                "wind_cdir_full": "east-northeast",
                "wind_dir": 69,
                "wind_gust_spd": 3.8,
                "wind_spd": 2.7
              }
            ],
            "lat": "45.04816",
            "lon": "20.08165",
            "state_code": "VO",
            "timezone": "Europe/Belgrade"
          },
        ));
      });

      List<ForecastWeather> forecastWeathers = await weatherRepo.getForecastWeather(city: "London");
      expect(forecastWeathers, isA<List<ForecastWeather>>());
    });
  });
}
